baseURL = "https://carlesbellver.net/"
canonifyURLs = true
languageCode = "ca-es"
title = "La vista cansada"
theme = "presbyopia"
publishDir = "public"
uglyurls = false
summaryLength = 50
DefaultContentLanguage = "ca"
paginate = 12

[params]
  author = "Carles Bellver Torlà"
  website = "https://carlesbellver.net"
  email = "carles@carlesbellver.net"
  avatar =  "/uploads/ulleres_200.jpg"
  description = ""
  MastodonUser = "carlesbellver"
  MastodonHost = "mastodon.social"
  TwitterUser = "carlesbellver"
  GitHubUser = "carlesbellver"
  paginationSinglePost = false
  style = "light"
  readMore = true
  mainSections = ["posts"]
  indexSections = ["posts", "contes", "llibres", "taller"]
  noPosts = 8
  webmentions = false
  fediverse = true
  lightbox = true
  stats = true
  chumby = false

[permalinks]
  posts = "/:year/:month/:day/:slug"

[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      typographer = false
    [markup.goldmark.renderer]
      unsafe = true
  
[menu]

  [[menu.main]]
    identifier = "onthisday"
    name = "Tal dia com avui"
    url = "/onthisday/"
    weight = 2

  [[menu.main]]
    identifier = "llibres"
    name = "Llibres"
    url = "/llibres/"
    weight = 4

  [[menu.main]]
    identifier = "taller"
    name = "Experiments"
    url = "/taller/"
    weight = 5

  [[menu.main]]
    identifier = "photos"
    name = "Fotos"
    url = "/photos/"
    weight = 6

  [[menu.main]]
    identifier = "search"
    name = "Cercar"
    url = "/archive/"
    weight = 7

[mediaTypes]
  [mediaTypes.'text/markdown']
    suffixes = ['md']
        
[outputFormats]
  [outputFormats.Markdown]
    isPlainText = true
    mediaType = 'text/markdown'
  [outputFormats.RSS]
    baseName = "feed"
  [outputFormats.JSON]
    baseName = "feed"
  [outputFormats.ArchiveHTML]
		mediaType = "text/html"
		path = "archive"
		baseName = "index"
		isPlainText = false
		notAlternative = true
	[outputFormats.FullArchiveJSON]
		mediaType = "application/json"
		path = "archive"
		baseName = "archive"
		isPlainText = true
		notAlternative = true
	[outputFormats.ArchiveJSON]
		mediaType = "application/json"
		path = "archive"
		baseName = "index"
		isPlainText = true
		notAlternative = true
	[outputFormats.PhotosHTML]
		mediaType = "text/html"
		path = "photos"
		baseName = "index"
		isPlainText = false
		notAlternative = true
	[outputFormats.PhotosJSON]
		mediaType = "application/json"
		path = "photos"
		baseName = "index"
		isPlainText = true
		notAlternative = true
    
	[outputs]
	  home = [ "HTML", "RSS", "JSON", "ArchiveHTML", "FullArchiveJSON", "ArchiveJSON", "PhotosJSON" ]
	  page = [ "HTML" ]
	  section = [ "HTML" ]
