name = "Presbyopia"
license = ""
description = "A minimal Hugo theme"
homepage = ""
tags = [
    "blog", 
    "responsive",
    "personal",
    "minimal", 
    "clean",
    "simple", 
    "light",
    "dark",
    "google-analytics",
    "mobile",
    "fast",
    "multilingual"
]
features = ["blog"]

[author]
    name = ""
    homepage = ""
